/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lap4;
import javax.swing.*;
/**
 *
 * @author HAI NAM
 */
public class bai3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai3.class.getName());

    /**
     * Creates new form bai3
     */
    public bai3() {
        initComponents();
        btnHuy.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtN = new javax.swing.JTextField();
        btnTinh = new javax.swing.JButton();
        lblKetQua = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        btnHuy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblDanhSach = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTinh.setText("Tính");
        btnTinh.addActionListener(this::btnTinhActionPerformed);

        lblKetQua.setText("Kết quả");

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(this::btnHuyActionPerformed);

        lblDanhSach.setText("So nguyen to:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblDanhSach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKetQua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTinh)
                        .addGap(43, 43, 43)
                        .addComponent(btnHuy)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        // TODO add your handling code here:
        String input = txtN.getText().trim();
    int n;
    try {
        if (input.isEmpty() || input.equals("Nhập N")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số N");
            return;
        }
        n = Integer.parseInt(input);
        if (n <= 2) {
            JOptionPane.showMessageDialog(this, "N phải lớn hơn 2");
            return;
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập số nguyên hợp lệ");
        return;
    }

    btnTinh.setEnabled(false);
    btnHuy.setEnabled(true);
    progressBar.setValue(0);
    lblKetQua.setText("Đang tính...");
    lblDanhSach.setText("");
    danhSach = new StringBuilder();

    currentWorker = new SwingWorker<Long, Integer>() {
        @Override
        protected Long doInBackground() {
            long sum = 0;
            for (int i = 2; i < n; i++) {
                if (isCancelled()) {
                    return sum;
                }
                if (isPrime(i)) {
                    sum += i;
                    publish(i);
                }
                int progress = (int) ((i * 100.0) / n);
                setProgress(progress);
                
                try {
            Thread.sleep(100);  
        } catch (InterruptedException ex) {
            return sum;   
        }
            }
            return sum;
        }

        @Override
        protected void process(java.util.List<Integer> chunks) {
            for (int soNguyenTo : chunks) {
                danhSach.append(soNguyenTo).append(" ");
            }
            lblDanhSach.setText(danhSach.toString());
        }

        @Override
        protected void done() {
            btnTinh.setEnabled(true);
            btnHuy.setEnabled(false);

            if (isCancelled()) {
                lblKetQua.setText("Đã hủy tác vụ");
                return;
            }

            try {
                long result = get();
                lblKetQua.setText("Tổng các số nguyên tố nhỏ hơn " + n + " = " + result);
                progressBar.setValue(100);
            } catch (Exception ex) {
                lblKetQua.setText("Có lỗi khi tính toán");
            }
        }
    };

    currentWorker.addPropertyChangeListener(evt2 -> {
        if ("progress".equals(evt2.getPropertyName())) {
            progressBar.setValue((int) evt2.getNewValue());
        }
    });

    currentWorker.execute();
    }//GEN-LAST:event_btnTinhActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        if (currentWorker != null && !currentWorker.isDone()) {
        currentWorker.cancel(true);
        btnHuy.setEnabled(false);
    
}
    }//GEN-LAST:event_btnHuyActionPerformed
private boolean isPrime(int n) {
    if (n < 2) return false;
    if (n == 2) return true;
    if (n % 2 == 0) return false;

    for (int i = 3; i <= Math.sqrt(n); i += 2) {
        if (n % i == 0) return false;
    }
    return true;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai3().setVisible(true));
    }
    private SwingWorker<Long, Integer> currentWorker;
    private StringBuilder danhSach;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDanhSach;
    private javax.swing.JLabel lblKetQua;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField txtN;
    // End of variables declaration//GEN-END:variables
}
