/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lap4;
import javax.swing.*;
/**
 *
 * @author HAI NAM
 */
public class dongho extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dongho.class.getName());

    /**
     * Creates new form dongho
     */
    public dongho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGiay = new javax.swing.JTextField();
        btnBatDau = new javax.swing.JButton();
        lblTieude = new javax.swing.JLabel();
        lblThoiGian = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtGiay.addActionListener(this::txtGiayActionPerformed);

        btnBatDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBatDau.setText("Bắt Đầu");
        btnBatDau.addActionListener(this::btnBatDauActionPerformed);

        lblTieude.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTieude.setText("Nhập số giây cần đếm:");

        lblThoiGian.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lblThoiGian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThoiGian.setText("00:00:00");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Thời gian còn lại:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTieude))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGiay))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTieude, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGiayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiayActionPerformed
        // TODO add your handling code here:
        btnBatDauActionPerformed(evt);
    }//GEN-LAST:event_txtGiayActionPerformed

    private void btnBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatDauActionPerformed
int giay;
    try {
        giay = Integer.parseInt(txtGiay.getText().trim());
        if (giay <= 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số giây lớn hơn 0!");
            return;
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Số giây không hợp lệ!");
        return;
    }

    btnBatDau.setEnabled(false);
    txtGiay.setEnabled(false);

    SwingWorker<Void, Integer> worker = new SwingWorker<Void, Integer>() {
        @Override
        protected Void doInBackground() throws Exception {
            for (int i = giay; i >= 0; i--) {
                publish(i);
                Thread.sleep(1000);
            }
            return null;
        }

        @Override
          protected void process(java.util.List<Integer> chunks) {
          int con = chunks.get(chunks.size() - 1);
          lblThoiGian.setText(formatThoiGian(con));
}

        @Override
        protected void done() {
            btnBatDau.setEnabled(true);
            txtGiay.setEnabled(true);
            lblThoiGian.setText(formatThoiGian(giay));
            JOptionPane.showMessageDialog(rootPane, "Hết giờ!");
        }
    };
    worker.execute();       
    }//GEN-LAST:event_btnBatDauActionPerformed
private String formatThoiGian(int tongGiay) {
    int gio = tongGiay / 3600;
    int phut = (tongGiay % 3600) / 60;
    int giay = tongGiay % 60;
    return String.format("%02d:%02d:%02d", gio, phut, giay);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dongho().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatDau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JLabel lblTieude;
    private javax.swing.JTextField txtGiay;
    // End of variables declaration//GEN-END:variables
}
